// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { readSupabaseBrowserConfig } from './env';

const supabaseConfig = readSupabaseBrowserConfig(import.meta.env);

export const hasSupabaseBrowserConfig = supabaseConfig !== null;

let browserClient: ReturnType<typeof createClient<Database>> | null = null;

export const getSupabaseBrowserClient = () => {
  if (!supabaseConfig) {
    return null;
  }

  if (!browserClient) {
    browserClient = createClient<Database>(
      supabaseConfig.url,
      supabaseConfig.anonKey
    );
  }

  return browserClient;
};

export const supabase = new Proxy({} as ReturnType<typeof createClient<Database>>, {
  get(_target, property, receiver) {
    const client = getSupabaseBrowserClient();
    if (!client) {
      throw new Error("Supabase URL or Anon Key is missing from environment variables.");
    }

    return Reflect.get(client, property, receiver);
  },
});
