-- Create sun_exposure_log table
CREATE TABLE public.sun_exposure_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  hours NUMERIC(4, 2) NOT NULL CHECK (hours > 0),
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Add comments to the table and columns
COMMENT ON TABLE public.sun_exposure_log IS 'Stores daily sun exposure logs for users.';
COMMENT ON COLUMN public.sun_exposure_log.user_id IS 'Foreign key to the user who logged the exposure.';
COMMENT ON COLUMN public.sun_exposure_log.date IS 'The date of the sun exposure.';
COMMENT ON COLUMN public.sun_exposure_log.hours IS 'Duration of sun exposure in hours (e.g., 1.5 for 1 hour 30 minutes).';
COMMENT ON COLUMN public.sun_exposure_log.created_at IS 'Timestamp of when the log was created.';

-- Enable Row Level Security (RLS)
ALTER TABLE public.sun_exposure_log ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
-- Users can insert their own sun exposure logs
CREATE POLICY "Allow users to insert their own sun exposure logs" 
ON public.sun_exposure_log
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Users can view their own sun exposure logs
CREATE POLICY "Allow users to view their own sun exposure logs" 
ON public.sun_exposure_log
FOR SELECT
USING (auth.uid() = user_id);

-- Users can update their own sun exposure logs
CREATE POLICY "Allow users to update their own sun exposure logs" 
ON public.sun_exposure_log
FOR UPDATE
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Users can delete their own sun exposure logs
CREATE POLICY "Allow users to delete their own sun exposure logs" 
ON public.sun_exposure_log
FOR DELETE
USING (auth.uid() = user_id);

-- Create an index on user_id and date for faster lookups
CREATE INDEX idx_sun_exposure_log_user_date ON public.sun_exposure_log(user_id, date);;
