// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhkhpwoxedcytetcjnob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoa2hwd294ZWRjeXRldGNqbm9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTcyMDMsImV4cCI6MjA1OTkzMzIwM30.LeyaHU6-CaG_rcmGrz8Gw2PBA2-Q-i2r7btP3HPdBus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);